// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiAOX34lyZ9o05BEmPL3W14v4QuUY53RQ',
    appId: '1:528358178403:android:5a425866aef6ad16e7c256',
    messagingSenderId: '528358178403',
    projectId: 'todoeasy-95dd4',
    storageBucket: 'todoeasy-95dd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo4e8160N0a3b7SD9Z60e_fwEUz06yifM',
    appId: '1:528358178403:ios:61d190211200695ce7c256',
    messagingSenderId: '528358178403',
    projectId: 'todoeasy-95dd4',
    storageBucket: 'todoeasy-95dd4.firebasestorage.app',
    iosBundleId: 'com.viren.todoeasy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq1ZC051zmst0jGwHVITIrKrns-OPOPdk',
    appId: '1:528358178403:web:065a9ae41cdefb3ee7c256',
    messagingSenderId: '528358178403',
    projectId: 'todoeasy-95dd4',
    authDomain: 'todoeasy-95dd4.firebaseapp.com',
    storageBucket: 'todoeasy-95dd4.firebasestorage.app',
    measurementId: 'G-82LD7BDS2X',
  );
}
