// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOJuDrfq1AvhU4Crnl12FUvC9FhrK93ho',
    appId: '1:498694689943:android:895d956fa956a072df05d2',
    messagingSenderId: '498694689943',
    projectId: 'todoist-88b0e',
    storageBucket: 'todoist-88b0e.firebasestorage.app',
    androidClientId:
        '498694689943-40h98qpqjln5chtfvmrg5f6ibv52vs30.apps.googleusercontent.com',
    iosClientId:
        '498694689943-m2h0lae8hob5l2g95bjkeg047k69nb5u.apps.googleusercontent.com',
    iosBundleId: 'com.viren.todoist',
    
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL2YipXpxmt6n1bmHJ3ZJGNF5ZE8yABiQ',
    appId: '1:498694689943:ios:f15a705574c90c7cdf05d2',
    messagingSenderId: '498694689943',
    projectId: 'todoist-88b0e',
    storageBucket: 'todoist-88b0e.firebasestorage.app',
    androidClientId:
        '498694689943-40h98qpqjln5chtfvmrg5f6ibv52vs30.apps.googleusercontent.com',
    iosClientId:
        '498694689943-m2h0lae8hob5l2g95bjkeg047k69nb5u.apps.googleusercontent.com',
    iosBundleId: 'com.viren.todoist',
  );
}
